server:
  port: 18080

spring:
  application:
    name: customer-stock-report-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://api.pneumaai.cn:5432/saylove02
    username: postgres
    password: SaySouler@3.1415
